language: javascript
before_install:
- npm install -g grunt-cli
install:
- npm install
script:
- npm run build
after_success:
- npm pack

# Deployment directives.
# Triggered when tags are pushed.
deploy:

  # Github Releases.
  - provider: releases
    api_key:
      secure: KA0ifNsoCwFJusMbk8ckyHda9pti6gdvitOtBnanmKt7xIGdjAHluXNgRD+feAO2ol7NZqtRvl7l+si7bvozntF22jGn07Vi5n+oREhYNdx23FdePAPog5yFq6mnGobqgN3mMaOFLCDv58zAs+p8N3GmUzPSHea1GMROuQA8uIj/huuB8dfRGyO3QfVX1M9pp5DvaOMuNMXHfv3Neh/RzMyFF7T4TtErJxtHD5xPk4zHJOKSiZPaaZGOdFCgY9U82wl7FkKe+InLpSHUvNlUlVy5n2RYbbeb1+81pE8OQXZBJmdOtgd06mCmwELKtI4nO7H5mX/wz0lbN3d1AtoT9Z9ZB6aQRDEpPDFxXLatYa45cb4n1sPmG3c3KbnzfZXJ++2mSV7N1WVlNTuUDylFbwewypkBwaUyPMYIxVAQTkibl+x0QU/WGhSFqlx0pS0NQ6rMwhPYb1BM+j0CdHTpe/4lVBtlytkBAriHGT90oruIF0fyGwXvyDPEVyZqH2pMfSAOkWFlKMb8IL+PpLlUq8k2/7qaL4INqlZR0ZLkR6TDJ4eSPu6H49DcoTHzDqC4+nh6lbDWP0WzVYzuYGjmrw/2IesoW/TWTMBtWu1Cn8LNz50DATlSy/B5tzXWehlnFWfYHImjUbhXL6f5mDlh6RR8IthP54CQNs9U4Ap3Jjo=
    file: preloader-js-$TRAVIS_TAG.tgz
    on:
      tags: true
  
  # NPM tag push.
  - provider: npm
    email: hqm.post@gmail.com
    skip_cleanup: true
    api_key:
      secure: mzDYoN3FDvFpX5gNrcNEe6FjH0VZ9IQoZuaC9KuO16qh0SiHyH1+eBDOyzGZ09HXFufnpRIpQtqJhRAC6fgqKYKWb92ymvvOIPpEK/oNfVQjAXLnL3imUngxtxk68GPL3P9yNSp/LlcYBbMd89Gmpr1uAElC1xnqYnLbmq0PJAUgywKoHzZC+ii2xvRqjWO+FWxQe/adLaWcjyuUiqC6jj5zBCHO8YlbBHb6Y6RCTl6xGTduO8AXYGnLBNyRBgN0du1Ib/0hYCBfJsMT+Z59j/qt5EYQrgFzZBRPQUVNLGpp8wzrZZsqGMYjNkHNVvkrSC61Q6MQjSN9fM7QDinUUyg+UGVZ8QMhRqt18AvqPbdaOL7Jt9eP/8FE2vO0RAFI0wBVdKGqJxgsLEzsGxGFzs/y63Jzy71aue3U31OGNrLh9DZ3oo7X241KqqXIVqQXNdFw1huaOsjlUmTXgHLqmeZTQYE9RhlMH0KT9RntMR4qxJTB0FVc67Csn/zvHLMDMmsTuJDLXuM2iUZawYT40Scigb7wxdTVIWPhIB3gJv0V10QxG0o+Mk7NyiR+nq/qIqwkDpyGVjSYGl0jmDQconKu++Ao6UKZoi+cPm8xLuA30SBbr3GlGXMaUZbJlxlFQgpc7UTGramCHnH1e3IPdK2qOOvnQiKypONZoayt7lk=
    on:
      tags: true
